
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config", "/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
      - "5555:5555" 
    volumes:
      - ./build/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml